/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zyj_jni_ZYJJniLib */

#ifndef _Included_com_zyj_jni_ZYJJniLib
#define _Included_com_zyj_jni_ZYJJniLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zyj_jni_ZYJJniLib
 * Method:    generateSettingCode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zyj_jni_ZYJJniLib_generateSettingCode
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
